{% set version = "3.9.2" %}

package:
  name: easybuild-easyconfigs
  version: {{ version }}

source:
  fn: easybuild-easyconfigs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-easyconfigs/easybuild-easyconfigs-{{ version }}.tar.gz
  sha256: d143e4ff0f2622b49babe865ca9468a3557dd2cb6825e2a96760e77e237152b4

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3
    - easybuild-easyblocks >=3.5

test:
  imports:
    - easybuild

about:
  home: http://hpcugent.github.com/easybuild
  license: GPL-2.0
  license_file: LICENSE
  summary: 'Easyconfig files are simple build specification files for EasyBuild,\nthat specify the build parameters for software packages (version, compiler toolchain, dependency versions, etc.).'
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
