{% set version = "4.3.2" %}

package:
  name: easybuild-easyconfigs
  version: {{ version }}

source:
  fn: easybuild-easyconfigs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/easybuild-easyconfigs/easybuild-easyconfigs-{{ version }}.tar.gz
  sha256: efa9d9874d813946c729e217494599492ac4ed02873c9f5a8f793eb9b0bc9e41

build:
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3
    - easybuild-easyblocks >=3.5

test:
  imports:
    - easybuild

about:
  home: http://hpcugent.github.com/easybuild
  license: GPL-2.0
  license_file: LICENSE
  summary: Easyconfig files are simple build specification files for EasyBuild,\nthat specify the build parameters for software packages (version, compiler toolchain, dependency versions, etc.).
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
