{% set version = "5.0.0" %}

package:
  name: easybuild-easyconfigs
  version: {{ version }}

source:
  fn: easybuild-easyconfigs-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/e/easybuild-easyconfigs/easybuild_easyconfigs-{{ version }}.tar.gz
  sha256: 3a15933e42a01badbf3d5aed3596a8f76f96fac1d5b56149e5be12bf4d7bef7c

build:
  number: 0
  skip: true  # [win or py3k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - easybuild-framework >=3
    - easybuild-easyblocks >=3.5

test:
  imports:
    - easybuild

about:
  home: http://hpcugent.github.com/easybuild
  license: GPL-2.0
  license_file: LICENSE
  summary: Easyconfig files are simple build specification files for EasyBuild,\nthat specify the build parameters for software packages (version, compiler toolchain, dependency versions, etc.).
  license_family: GPL2

extra:
  recipe-maintainers:
    - jerowe
    - boegel
