travis:
  secure:
    BINSTAR_TOKEN: Qdwv2vOwH3UXGHusdEQXfXvVKRlhS+Kdv7cz5hucyFgOh2n9DZXWCCe3zaCoTnzxSlRRvURtZX2koa3hzEjNEwj5X9+FObyox6rUKal9MUdroZU24Phd/z/em3CV5n7iWO3tcvDbbPlf3p4wF4ox54OC9LWzygwz4ZtL02bJi6G0UdPxMShKWL7Uz9IVqNNzXcyookhAZrheinqZa7T2RkgLfOD/g3GFTVOoHb59QiHpGObcvYEAMHiYktJ5qlNQ5pXWN/oIz57i+0vALO2S3TsFJkX8sAQktHrV2XG3PCUE7pz+rbinyvgWWi6k7TuXNIma1ocTjtR0npa8jBQsoGLnL2guMUDjeUmLgKZn5ErVSbZOrixs88Way14/izHcKA/6W9taDnkuT6vawwOqvNYbv3qJ+x6NWv63+4aenVO/QaTd/pqyCAHky+TVBZHxOem44MpdFptXRDrwsYoRagFLr/O64mzm13/R4zjxyrzc0lzv1f9dBDzJapo+Z4/3+XG6fOzPupzGUeSzpyAPE+aN7A8CMPKxJbKyoyIZIt6vkPqdHrGem1iv+P9An/GhGg7zKMM7E1qFsiBqjbVadUA46k0amvlBb0gXpZ8CXGmISJq7WK8d9lTYIGJoHrGTwJgPFt67b9mfGDTylWOzdXqDX1E1WlXOt5IOZGSVB78=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
