travis:
  secure:
    BINSTAR_TOKEN: MNDR6XmUKUV9e/rc8EoEwVyk2qTBn99C4MuxRpojJ/uvbYDLfkstxPDWtQPw5BsJZ5tuhZEaBpE+yueGpiPgyA7llwv5HbnezPwiI5rcOVHhKR3fBOb3G9dQ0UOYYhVmqGAaSjw+MKZRiUgNoD+vBYPrOZXgYChQfVJF5ULtHesLl/rC4RGENzPZI2zqmFLolb2eMRHCEpgB9mMFXYUuR0281akz8eXz7G4r4x3JIVGO70ziUsUcKCgb3Gr0jnGk8kkjAMVE7oP6CA0O9ikBX5szOtSM0ghP5cwVvef6nzEKuB0fudEt5fBF7cu5hKtH9Vv84E8fnEdyvNH/EmnqQHQECbn+Pp1KHnk/bySMT45TTQk8JyPjZ1YG0T73L49ODA0rCQGxZUaPOV6BqiYZHTd8ruf8m9n6E5PdOYJY6Sy07fOtrVBv+oF6OWiNZ5ClL8TiF4LeJXKZuTHu6pQ/PY/5uIdThuRn+CoR2jAN2quwRVQsUIvaimoNcirwl0BJlP3KZiJwRR9XhRuwRNw5MoYHJsfFEJr+jYwpbzQqqlN0K+54V02gLG9ftaneCLZ9B+cn2hI0bBNfu8wLMctYpZLmcReOnb+Ec5ie9uONz0rs1+ceKxS7mlNyRrN5d3xQnK5o9eRGWAw1w/aoTCBVKpbMy1b5Km/pv12k88JI4SQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
